name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"

jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        # set the username hardcoded
        SVN_USERNAME: wprepublic
        # password using secrets
        SVN_PASSWORD: ${{ secrets.DEPLOY_PASS }}
        # Explicity declare the WP.org slug for safety
        SLUG: wp-hide-backed-notices